version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-net
  app:
    container_name: app
    build: ./
    env_file: .env
    environment:
      - PORT=3000
      - DB=mongodb://mongo:27017/todos
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    external_links:
      - mongo
    networks:
      - my-net

networks:
  my-net:
  